---
params:
  anon_path: "data/applications.csv" 
output: 
  html_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(include = FALSE)
library(magrittr)
library(projectutils)
PROJECT_ID <- "{{{project_id}}}"
```

---
title: "Public project data `r PROJECT_ID`"
---

```{r}
#read from rds file
proj <- readr::read_rds(glue::glue("{PROJECT_ID}.rds"))
```

```{r}
# properties set through the constructor -----
# only uncomment if you want to change something
# you can also create the object again with correct parameters
# proj$name <- "an awesome new title" 
# proj$start_ym <- "2021-03"
# proj$project_id <- "2021-03-HAC"

# basic properties ---------------
proj$end_ym <- "1970-02"
proj$end_ym_predicted <- "1970-01"

# misc
proj$is_internal <- FALSE
proj$slack_channel <- "foochannel"
# urls
proj$num_gh_issue <- 10000
proj$url_git_repo <- "https://github.com/CorrelAid/foobar"
proj$url_ideation_pad <- "https://pad.correlaid.org/aaaaaaaaaaaaaaaaa"

# publish to website
proj$is_public <- FALSE
proj$slug <- "a-slug-for-the-website"

# RELATED TABLES ----------------
# set status
projectutils::status
proj$set_status(status = "Team selection / Onboarding  / Kickoff")
proj$status_id

# set local chapters
projectutils::local_chapters
proj$add_local_chapter(lc_name = "munich")
proj$add_local_chapter(lc_name = "paris")
proj$add_local_chapter("berlin")
proj$local_chapters

# add tags
available_tags <- projectutils::tags
available_tags
proj$add_tag("data", "administrative")
proj$add_tag("lc", "berlin")
proj$add_tag("internal")
proj$tags
```



# Description of the project 

```{r proj-description}
get_description_section <- function(section) {
    de <- readr::read_lines(glue::glue("de/{section}.md")) %>% paste(collapse = "\n")
    en <- readr::read_lines(glue::glue("en/{section}.md")) %>% paste(collapse = "\n")
    list(en = en, de = de)
}

desc <- Description$new(PROJECT_ID)
desc$title <- list(
     de = "",
     en = ""
)
desc$summary <- get_description_section("00_summary")
desc$problem <- get_description_section("01_problem")
desc$data <- get_description_section("02_data")
desc$approach <- get_description_section("03_approach")
desc$impact <- get_description_section("04_impact")
desc$further_links <- list(
     de = "",
     en = ""
)
proj$description <- desc

```

```{r}
# tibble representation of a project
proj$to_tibble()$tags
proj$to_tibble()$url_ideation_pad
```

```{r}
# tables
proj$get_sql_tables()
```


```{r}
# write to rds file
proj %>% readr::write_rds(glue::glue("{PROJECT_ID}.rds"))
```