---
params:
  applicant_id: 1
  anon_path: "data/applications_anonymized.csv"
output: pdf_document

---
<!-- THIS FILE IS NOT SUPPOSED TO BE KNITTED BY HAND
    INSTEAD IT IS KNIT AUTOMATICALLY 
    BY THE APPLICATIONS_REPORT.RMD FILE FOR EACH APPLICANT.
    YOU CAN EDIT THIS FILE IF YOU WANT TO CHANGE THE INFORMATION DISPLAYED FOR EACH APPLICANT
-->
```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)

library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(readr)
library(stringr)
library(forcats)

lvls <- tibble(level_num = c(0, 1, 2, 3), level = c("beginner", "user", "advanced", "expert"))
theme_set(theme_bw())
```

```{r message=FALSE}
appl <- readr::read_csv(params$anon_path, col_types = cols())
a <- appl %>% 
  filter(applicant_id == params$applicant_id)
```

```{r}
# data set with all applicants
tmp_all <- appl %>% 
  select(applicant_id, starts_with(c("skills", "techniques", "topics"))) %>% 
  pivot_longer(starts_with(c("skills", "techniques", "topics")), names_to = "category", values_to = "level") %>% 
  mutate(question = stringr::str_extract(category, "skills|techniques|topics")) %>% 
  mutate(category = stringr::str_replace(category, "skills_|techniques_|topics_", "")) %>% 
  rownames_to_column() %>% 
  left_join(lvls, by = "level") %>% 
  mutate(is_applicant_val = applicant_id == params$applicant_id)

tmp_applicant <- tmp_all %>% 
  filter(applicant_id == params$applicant_id)
```

## Applicant `r a$applicant_id` (`r a$project_role`) {#applicant-`r a$applicant_id`}
**Gender**: `r a$gender`

**Project role**: `r a$project_role`

**What skills qualify you?**

`r a$motivation_skills`

**Why do you want to get involved?**

`r a$motivation_why_involved`

### Self-rated experience with skills, techniques and topics 

```{r fig.height=6, fig.width=6}
theme_set(theme_bw())
ggplot(tmp_applicant, aes(x = category, y = level_num, group = question)) +
  geom_segment(aes(
    x = category,
    xend = category,
    y = 0,
    yend = level_num
  )) +
  geom_point(size = 3, color = "#3863a2") +
  coord_flip() +
  theme(
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.position = "none"
  ) +
  scale_y_continuous(
    "level",
    limits = c(0, max(lvls$level_num)),
    breaks = seq(0, max(lvls$level_num), 1),
    labels = lvls$level
  ) +
  facet_wrap( ~ question, nrow = 3, scales = "free_y") +
  xlab("")
```

```{r fig.width=6, fig.height=8}
tmp_all_highlight <- tmp_all %>%
  semi_join(tmp_applicant, by = c("category", "level")) %>%
  mutate(this_applicant = TRUE) %>%
  bind_rows(tmp_all %>%
    anti_join(tmp_applicant, by = c("category", "level")) %>%
    mutate(this_applicant = FALSE)) %>%
  mutate(
    category = fct_inorder(category),
    highlight = if_else(this_applicant,
      question,
      NA_character_
    )
  )

ggplot(tmp_all_highlight, aes(
  x = fct_reorder(level, level_num),
  fill = highlight
)) +
  geom_bar(width = 1) +
  scale_x_discrete(labels = lvls$level) +
  scale_y_continuous(breaks = c(0, 20)) +
  scale_fill_discrete(
    name = NULL,
    na.value = "#d9d9d9",
    breaks = unique(tmp_all$question)
  ) +
  facet_wrap(~category, ncol = 1, strip.position = "left") +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.spacing = unit(0, "pt"),
    panel.grid = element_blank(),
    panel.grid.major.y = element_line("grey92"),
    strip.text.y.left = element_text(angle = 0, hjust = 1),
    legend.position = "bottom"
  ) +
  labs(x = NULL, y = NULL)
```

```{r fig.height=6, fig.width=6, warning=FALSE}
ggplot(tmp_all_highlight, aes(
  x = fct_reorder(level, level_num),
  alpha = this_applicant,
  fill = question
)) +
  geom_bar(width = 1) +
  scale_x_discrete(labels = c("B", "U", "A", "E")) +
  scale_alpha_discrete(range = c(.25, 1), guide = "none") +
  facet_wrap(~category, ncol = 4) +
  theme_grey() +
  theme(
    panel.grid = element_blank(),
    panel.grid.major.y = element_line("grey92"),
    axis.text.x = element_text(size = rel(1.25)),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    legend.position = "bottom"
  ) +
  labs(x = NULL, y = NULL, caption = "B: Beginner, U: User, A: Advanced, E: Expert")
```

