---
params:
  anon_path: "data/applications.csv"
 output: 
  html_document:
    toc: true
    toc_depth: 2
title: "Project report `r toupper(params$project_id)`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(include = FALSE)
```

```{r}
PROJECT_ID <- "{{{project_id}}}"
params$project_id  <- PROJECT_ID

proj <- Project$new(PROJECT_ID, "")

# properties set through the constructor -----
# only uncomment if you want to change something
# you can also create the object again with correct parameters
# proj$name <- "an awesome new title" 
# proj$start_ym <- "2021-03"
# proj$project_id <- "2021-03-HAC"

# basic properties ---------------
proj$end_ym <- "1970-02"
proj$end_ym_predicted <- "1970-01"

# misc
proj$is_internal <- FALSE
proj$slack_channel <- "foochannel"
# urls
proj$url_gh_issue <- 10000
proj$url_git_repo <- "https://github.com/CorrelAid/foobar"
proj$url_ideation_pad <- "https://pad.correlaid.org/aaaaaaaaaaaaaaaaa"

# publish to website
proj$is_public <- FALSE
proj$slug <- "a-slug-for-the-website"

# RELATED TABLES ----------------
# set status
projectutils::status
proj$set_status(status = "Team selection / Onboarding  / Kickoff")
proj$status_id

# set local chapters
projectutils::local_chapters
proj$add_local_chapter(lc_name = "munich")
proj$add_local_chapter(lc_name = "paris")
proj$add_local_chapter("berlin")
proj$local_chapters

# add tags
available_tags <- projectutils::tags
available_tags
proj$add_tag("data", "administrative")
proj$add_tag("lc", "berlin")
proj$add_tag("internal")
proj$tags
```

```{r}
# Project team members
members <- tibble::tribble(
    ~volunteer_id, ~role,
    2, "team_trainee",
    43, "team_member", 
    92, "team_member", 
    42, "team_lead"
)
members$end_active_ym <- "2021-02"
members %>% 
    purrr::pmap(proj$add_project_member)

proj$project_members
```

# Description of the project 


```{r}
# tibble representation of a project
proj$to_tibble()$tags
proj$to_tibble()$url_ideation_pad
```